### ISSUE TITLE
Error on fresh install of wisp

### ISSUE THREAD

**Issue by zcaudate** [Gozala/wisp#109]
I did a fresh install of wisp and am getting the following error:

```
> npm install -g wisp
> wisp
=> (+ 1 1)
```

TypeError: Cannot convert null to object
    at SourceMapGenerator_setSourceContent [as setSourceContent](/usr/local/lib/node_modules/wisp/node_modules/escodegen/node_modules/source-map/lib/source-map/source-map-generator.js:142:43)
    at /usr/local/lib/node_modules/wisp/backend/escodegen/generator.js:111:36
    at generate (/usr/local/lib/node_modules/wisp/backend/escodegen/generator.js:117:11)
    at inputø1 (/usr/local/lib/node_modules/wisp/repl.js:36:41)
    at /usr/local/lib/node_modules/wisp/repl.js:40:19
    at evaluateCode (/usr/local/lib/node_modules/wisp/repl.js:52:11)
    at /usr/local/lib/node_modules/wisp/repl.js:60:28
    at REPLServer.evaluate [as eval](/usr/local/lib/node_modules/wisp/repl.js:62:15)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)

**Comment by pocka** [comment]
This seems to be a source-map's issue (mozilla/source-map#131).
It has fixed in source-map@0.1.39, and so re-install escodegen may solves this problem (escodegen now depend on `"source-map": "~0.2.0"`).

**Comment by chr15m** [comment]
@zcaudate ♥ thank you!
