### ISSUE TITLE
repl ignores first character of a statement

### ISSUE THREAD

**Issue by riatzukiza** [Gozala/wisp#141]
When running the repl the first character of any statement is sliced off

```
=> (console.log "wisp")
SyntaxError: Unmatched delimiter 
line:0
column:18
    at SyntaxError (native)
    at /usr/local/node/lib/node_modules/wisp/reader.js:107:27
    at readerError (/usr/local/node/lib/node_modules/wisp/reader.js:114:11)
    at readUnmatchedDelimiter (/usr/local/node/lib/node_modules/wisp/reader.js:257:16)
    at /usr/local/node/lib/node_modules/wisp/reader.js:440:40
    at readForm (/usr/local/node/lib/node_modules/wisp/reader.js:451:11)
    at /usr/local/node/lib/node_modules/wisp/reader.js:459:233
    at loop (/usr/local/node/lib/node_modules/wisp/reader.js:461:19)
    at read (/usr/local/node/lib/node_modules/wisp/reader.js:464:11)
    at /usr/local/node/lib/node_modules/wisp/compiler.js:40:24
=> ((console.log "wisp")
wisp
```

**Comment by sarahlim** [comment]
Same here :(

**Comment by elsehow** [comment]
same

**Comment by chr15m** [comment]
Merged, thanks @pocka!
