### ISSUE TITLE
wisp is ignoring first char is repl input

### ISSUE THREAD

**Issue by elsehow** [Gozala/wisp#143]
```
=> nil
repl:1
il;
^
ReferenceError: il is not defined
    at repl:1:1
    at Object.exports.runInContext (vm.js:44:17)
    at /Users/ffff/Projects/wisp-playing/node_modules/wisp/repl.js:43:46
    at /Users/ffff/Projects/wisp-playing/node_modules/wisp/repl.js:47:19
    at evaluateCode (/Users/ffff/Projects/wisp-playing/node_modules/wisp/repl.js:52:11)
    at /Users/ffff/Projects/wisp-playing/node_modules/wisp/repl.js:60:28
    at REPLServer.evaluate (/Users/ffff/Projects/wisp-playing/node_modules/wisp/repl.js:62:15)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:427:12)
```

`node -v` v5.7.0

`npm -v` 3.7.5

**Comment by elsehow** [comment]
sorry, same as #141
