### ISSUE TITLE
Browser runtime bundle HOWTO

### ISSUE THREAD

**Issue by rcarmo** [Gozala/wisp#71]
It would be exceedingly nice to have a simple HOWTO explaining how to build a browser bundle that packaged the runtime and one's app.

I've been working through the interactivate-wisp repo to figure it all out (and am still wrestling with browserify to get everything right), but I don't think most folk would take the time...

**Comment by chr15m** [comment]
@rcarmo I know you don't have a lot of time but can you let me know if https://gozala.github.com/wisp/ fixes this?

The `wisp.min.js` file is created thus:

`make dist/wisp.min.js`

If that's sufficient for you we can go ahead and close this ticket.

**Comment by rcarmo** [comment]
Sure. Will test with a blank VM/container and report back.

**Comment by rcarmo** [comment]
Quick update: I've just noticed this TODO as overdue but haven't come round to it.

**Comment by rcarmo** [comment]
Okay. Finally took a stab at this with a Docker container:

```bash
$  docker run -ti ubuntu:xenial /bin/bash

# after installing git and npm:

root@60d09bfb7bbb:/# npm install wisp
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:821:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  git://github.com/Constellation/escodegen.git#master resetting remote /root/.npm/_git-remotes/git-github-com-Constellation-escodegen-git-master-e48bf337 because of error: { [Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }
/
`-- wisp@0.10.0 
  +-- base64-encode@1.0.1 
  +-- commander@2.9.0 
  | `-- graceful-readlink@1.0.1 
  `-- escodegen@1.8.1  (git://github.com/Constellation/escodegen.git#719de3033c4a9a0df27f698c47b48d2af7241835)
    +-- esprima@2.7.3 
    +-- estraverse@1.9.3 
    +-- esutils@2.0.2 
    +-- optionator@0.8.2 
    | +-- deep-is@0.1.3 
    | +-- fast-levenshtein@2.0.6 
    | +-- levn@0.3.0 
    | +-- prelude-ls@1.1.2 
    | +-- type-check@0.3.2 
    | `-- wordwrap@1.0.0 
    `-- source-map@0.2.0 
      `-- amdefine@1.0.1 

npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.
root@60d09bfb7bbb:/# wisp
bash: wisp: command not found
```

**Comment by rcarmo** [comment]
Hmmm.

```bash
root@60d09bfb7bbb:~# git clone https://github.com/Gozala/wisp.git
Cloning into 'wisp'...
remote: Counting objects: 4958, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 4958 (delta 7), reused 0 (delta 0), pack-reused 4937
Receiving objects: 100% (4958/4958), 2.38 MiB | 1.14 MiB/s, done.
Resolving deltas: 100% (2831/2831), done.
Checking connectivity... done.
root@60d09bfb7bbb:~# cd wisp/
root@60d09bfb7bbb:~/wisp# make dist/wisp.min.js
mkdir -p dist
./node_modules/wisp/bin/wisp.js < src/engine/runner.wisp > runner.js
/bin/sh: 1: ./node_modules/wisp/bin/wisp.js: not found
Makefile:95: recipe for target 'dist/wisp.js' failed
make: *** [dist/wisp.js] Error 127
root@60d09bfb7bbb:~/wisp# 
```

So what am I missing?

**Comment by vendethiel** [comment]
Isn't it because recent npm versions changed where the bins are stored?

**Comment by chr15m** [comment]
@rcarmo thanks for testing, i think i know what is going on here.

@vendethiel i think it's just because it is not installing wisp as a dependency.

Will try to fix.
